# docker-compose.prod.yml
services:
  # Django 웹 애플리케이션
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod  # Dockerfile.prod로 빌드
    command: gunicorn drfproject.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: drfproject.settings.prod
      TZ: "Asia/Seoul"
      # 필요하면 아래에 DB 환경변수 추가
      # POSTGRES_DB: db
      # POSTGRES_USER: root
      # POSTGRES_PASSWORD: yourstrongpass
      # POSTGRES_HOST: db
      # POSTGRES_PORT: "5432"
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - "8000"
    entrypoint: ["sh", "config/docker/entrypoint.prod.sh"]

  # Nginx 리버스 프록시
  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      TZ: "Asia/Seoul"

volumes:
  static:
  media:
