# docker-compose.prod.yml
services:
  # Django 웹 애플리케이션
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod    # Dockerfile.prod를 사용해 이미지를 빌드
    # 컨테이너가 시작될 때 Gunicorn 웹 서버를 사용하여 Django 애플리케이션을 실행
    command: gunicorn drfproject.wsgi:application --bind 0.0.0.0:8000
    environment: # settings.prod를 설정 모듈로 설정
      DJANGO_SETTINGS_MODULE: drfproject.settings.dev 
    env_file:
     - .env # 환경 변수를 .env 파일에서 로드

    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - "8000"
    entrypoint: ["sh", "config/docker/entrypoint.prod.sh"]

  # Nginx 리버스 프록시
  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      TZ: "Asia/Seoul"

volumes:
  static:
  media:
